import React, { useState, useMemo, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Psychology, 
  LocationOn, 
  ArrowForward, 
  VerifiedUser, 
  MoodBad, 
  ChildCare, 
  SentimentVeryDissatisfied, 
  Chat, 
  CalendarMonth, 
  Spa, 
  CheckCircle,
  Share,
  Star,
  PhotoCamera,
  PinDrop,
  Send,
  Home as HomeIcon,
  MedicalServices,
  Group,
  Favorite,
  Verified,
  Settings,
  Public,
  Add,
  Delete,
  Edit,
  Close,
  Info,
  AssignmentTurnedIn,
  MenuIcon,
  ArrowBack,
  AccessTime
} from './components/Icons';
import { 
  Instagram, 
  Facebook, 
  Linkedin as LinkedIn, 
  Wifi, 
  ConciergeBell, 
  Volume2, 
  Snowflake, 
  ShieldCheck,
  Accessibility,
  LogOut,
  LogIn,
  User,
  Baby,
  Heart,
  Brain,
  Briefcase,
  Users,
  ParkingCircle,
  Stethoscope,
  GraduationCap,
  Sun,
  Cloud,
  CloudSun,
  Moon,
  Trash2,
  Edit2,
  RefreshCw,
  CreditCard,
  AlertTriangle,
  Code,
  Target,
  Check,
  AlertCircle,
  Clock,
  MessageCircle
} from 'lucide-react';
import FloatingWhatsApp from './components/FloatingWhatsApp';
import FloatingTelegram from './components/FloatingTelegram';
import Cropper from 'react-easy-crop';
import { Screen, TransitionType, Specialist, Approach, HomeSettings, AgeGroup, Shift, InsurancePlan, SubleaseRoom, SubleaseBooking, PsicoeducacaoArticle } from './types';
import { DEFAULT_HOME_SETTINGS, DEFAULT_SPECIALISTS, DEFAULT_APPROACHES, DEFAULT_TESTIMONIALS, CLINICA_LOGO_URL, DEFAULT_SUBLEASE_ROOMS } from './constants';
import { 
  getHomeSettings, 
  saveHomeSettings, 
  getSpecialists, 
  saveSpecialists, 
  getApproaches, 
  saveApproaches, 
  getInsurancePlans, 
  saveInsurancePlans,
  getSubleaseRooms,
  saveSubleaseRooms,
  getSubleaseBookings,
  saveSubleaseBooking,
  updateSubleaseBookingStatus,
  updateSpecialistSchedule,
  loginWithGoogle,
  logout as firebaseLogout,
  forceResetFirebase,
  auth,
  COLLECTIONS,
  DOCS,
  db,
  getPsicoeducacaoArticles,
  savePsicoeducacaoArticles,
  ensureSpecialistsSlugs
} from './lib/firebase';
import { onAuthStateChanged } from 'firebase/auth';
import { onSnapshot, collection, doc, getDocs, setDoc, updateDoc } from 'firebase/firestore';
import { trackWhatsAppClick, trackScheduleClick, trackFormSubmit, trackSpecialistProfileView } from './analytics';
import { WHATSAPP_URL, WHATSAPP_DISPLAY_NUMBER } from './contact';
